In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [ ]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Discount Applied        3900 non-null   object
 13  Previous Purchases      3900 non-null   int64
 14  Payment Method          3900 non-null   object
 15  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(11)
memory usage: 487.6+ KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'discount_applied',
       'previous_purchases', 'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [10]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [11]:
labels = ['Young Adult','Adult','MIddle-Aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels = labels)

In [12]:
df[['age','age_group']].head(10)

   age    age_group
0   55  MIddle-Aged
1   19  Young Adult
2   50  MIddle-Aged
3   21  Young Adult
4   45  MIddle-Aged
5   46  MIddle-Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  MIddle-Aged

In [13]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quaterly': 90,
    'Biannual': 180,
    'Yearly': 365
}
df['purschase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df['purschase_frequency_days'] = df['frequency_of_purchases'].head(10)

In [15]:
df[['discount_applied','subscription_status']].head(10)

  discount_applied subscription_status
0              Yes                 Yes
1              Yes                 Yes
2              Yes                 Yes
3              Yes                 Yes
4              Yes                 Yes
5              Yes                 Yes
6              Yes                 Yes
7              Yes                 Yes
8              Yes                 Yes
9              Yes                 Yes

In [16]:
(df['discount_applied'] == df['subscription_status']).all()

np.False_

In [18]:
import sqlite3
import pandas as pd


csv_file_name = "customer_shopping_behavior.csv"
df = pd.read_csv(csv_file_name)


conn = sqlite3.connect('customer.db')


table_name = "customer_data"
df.to_sql(table_name, conn, if_exists='replace', index=False)

print(f"🎉 Database successfully created")
conn.close()

🎉 Database successfully created

In [19]:

conn = sqlite3.connect('customer.db')
query = "SELECT * FROM customer_data LIMIT 5;"

In [20]:
df_result = pd.read_sql_query(query, conn)
conn.close()

In [21]:
df_result

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Yes,31,PayPal,Annually

In [22]:
%load_ext sql

In [23]:
import sqlite3
import pandas as pd

# 1. Database se seedha connect karein
conn = sqlite3.connect('customer.db')

# 2. Apni query ko string ke roop me likhein
query = """
SELECT gender, SUM("Previous Purchases") as total_purchase
FROM customer_data
GROUP BY gender;
"""

# 3. Pandas ke roop me query run karein (Ye kabhi crash nahi hota)
df_result = pd.read_sql_query(query, conn)

# 4. Connection close karein
conn.close()

# 5. Output display karein
df_result

   Gender  total_purchase
0  Female           30696
1    Male           68175

In [24]:
import sqlite3
import pandas as pd

# Ye function aapka baar-baar upar-niche ka kaam khud karega
def run_sql(query):
    conn = sqlite3.connect('customer.db')
    try:
        df_res = pd.read_sql_query(query, conn)
        conn.close()
        return df_res
    except Exception as e:
        conn.close()
        print(f"Error: {e}")

In [25]:
run_sql("""
SELECT "Customer ID", "Previous Purchases"
FROM customer_data
WHERE "Discount Applied" = 'Yes'
  AND "Previous Purchases" >= (SELECT AVG("Previous Purchases") FROM customer_data);
""")

     Customer ID  Previous Purchases
0              4                  49
1              5                  31
2              7                  49
3             11                  26
4             13                  37
..           ...                 ...
827         1666                  49
828         1667                  47
829         1669                  28
830         1674                  49
831         1677                  34

[832 rows x 2 columns]

In [26]:
run_sql("""
select "Item Purchased", AVG("Review Rating") as avg_rating
from customer_data
group by "Item Purchased"
order by avg_rating desc
limit 5 ;"""
)

  Item Purchased  avg_rating
0         Gloves    3.864286
1        Sandals    3.841250
2          Boots    3.812500
3            Hat    3.806494
4        T-shirt    3.782993

In [27]:
run_sql("""
SELECT "Shipping Type", AVG("Previous Purchases")
FROM customer_data
WHERE "Shipping Type" IN ('Standard', 'Express', 'standard', 'express')
GROUP BY "Shipping Type";
""")

Empty DataFrame
Columns: ["Shipping Type", AVG("Previous Purchases")]
Index: []

In [28]:
run_sql("""
select "Subscription Status", COUNT("Customer Id")as "Total Customers",
AVG("Previous Purchases") as "Average Purchases",
SUM("Previous Purchases") as "Total Purchases"
from customer_data
group by "Subscription Status"
order by "Total Purchases" , "Average Purchases" desc;
""")

  Subscription Status  Total Customers  Average Purchases  Total Purchases
0                 Yes             1053          26.084520            27467
1                  No             2847          25.080436            71404

In [29]:
run_sql("""
select "Item Purchased", SUM(CASE when "Discount Applied"='yes' Then 1 ELSE 0 END )/COUNT(*) as "Discount Rate"
from customer_Data
group by "Item Purchased"
order by "Discount Rate" desc
limit 5;
""")

  Item Purchased  Discount Rate
0        T-shirt              0
1        Sweater              0
2     Sunglasses              0
3          Socks              0
4       Sneakers              0

In [30]:
run_sql("""
WITH "customer Type" AS (
    SELECT "Customer ID",
           CASE
               WHEN "Previous Purchases" = 1 THEN 'New'
               WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS "customer_segment"
    FROM customer_data
)
SELECT "customer_segment", COUNT(*) AS "number of customer"
FROM "customer Type"
GROUP BY "customer_segment"
ORDER BY "number of customer" DESC;
""")

  customer_segment  number of customer
0            Loyal                3116
1        Returning                 701
2              New                  83

In [31]:
run_sql("""
WITH "Item Counts" AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS "Total Orders",
           ROW_NUMBER() OVER(
               PARTITION BY "Category"
               ORDER BY COUNT("Customer ID") DESC
           ) AS "Item Rank"
    FROM customer_data
    GROUP BY "Category", "Item Purchased"
)
SELECT "Item Rank", "Category", "Item Purchased", "Total Orders"
FROM "Item Counts";
""")

    Item Rank     Category Item Purchased  Total Orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           4  Accessories          Scarf           157
4           5  Accessories            Hat           154
5           6  Accessories        Handbag           153
6           7  Accessories       Backpack           143
7           8  Accessories         Gloves           140
8           1     Clothing          Pants           171
9           2     Clothing         Blouse           171
10          3     Clothing          Shirt           169
11          4     Clothing          Dress           166
12          5     Clothing        Sweater           164
13          6     Clothing          Socks           159
14          7     Clothing          Skirt           158
15          8     Clothing         Shorts           157
16          9     Clothing         Hoodie           151
17         10     Clothing        T-shirt           147
18         11     Clothing          Jeans           124
19          1     Footwear        Sandals           160
20          2     Footwear          Shoes           150
21          3     Footwear       Sneakers           145
22          4     Footwear          Boots           144
23          1    Outerwear         Jacket           163
24          2    Outerwear           Coat           161

In [32]:
run_sql("""
select "Subscroption Status",
COUNT("Customer ID")as "Total Customers"
from customer_data
where "Previos Purchases" > 5
group by "Subscription Status"
""")

  "Subscroption Status"  Total Customers
0   Subscroption Status             2847
1   Subscroption Status             1053

In [33]:
run_sql("""
SELECT
    CASE
        WHEN Age BETWEEN 18 AND 30 THEN 'Young'
        WHEN Age BETWEEN 31 AND 50 THEN 'Adult'
        ELSE 'Senior'
    END AS "Age Group",
    SUM("Previous Purchases") AS "Total Revenue"
FROM customer_data
GROUP BY "Age Group"
ORDER BY "Total Revenue" DESC;
""")

  Age Group  Total Revenue
0    Senior          38773
1     Adult          36547
2     Young          23551

In [34]:
import sqlite3
import pandas as pd

# 1. Database se connect karein
conn = sqlite3.connect('customer.db')

# 2. Poora data nikal kar pandas mein laayein
df = pd.read_sql_query("SELECT * FROM customer_data", conn)
conn.close()

# 3. Ise apne laptop mein ek nayi CSV file banakar save kar dein
df.to_csv('customer_cleaned_data.csv', index=False)
print("File successfully saved as customer_cleaned_data.csv!")

File successfully saved as customer_cleaned_data.csv!